apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-agent-2-backend
  namespace: furniaizer
  labels:
    app: ai-agent-2-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-agent-2-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ai-agent-2-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/teamshackathon/prod/ai-agent-2-backend:latest
        imagePullPolicy: Always
        command: ["uvicorn"]
        args: ["main:app", "--host", "0.0.0.0", "--port", "8000"]
        env:
        - name: ALLOWED_ORIGINS
          value: "http://ai-agent-2-frontend-service:3001,http://ai-agent-2-frontend-service.furniaizer:3001,http://ai-agent-2-frontend-service.furniaizer.svc.cluster.local:3001"
        ports:
        - containerPort: 8000
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /api/v1/healthcheck/liveness
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/healthcheck/readiness
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
