apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-agent-2-backend
  namespace: furniaizer
  labels:
    app: ai-agent-2-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-agent-2-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ai-agent-2-backend
    spec:
      initContainers:
      - name: discord-notification
        image: alpine/curl
        command:
        - sh
        - -c
        - |
          WEBHOOK_URL="${DISCORD_WEBHOOK_URL}"
          POD_NAME="${POD_NAME:-$(hostname)}"
          NAMESPACE="${POD_NAMESPACE:-default}"
          DEPLOYMENT="ai-agent-2-backend"
          PRODUCTION_URL="${PRODUCTION_URL:-N/A}"
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{
              \"embeds\": [{
                \"title\": \"🚀 Pod Restarted\",
                \"description\": \"A pod has been restarted in the Kubernetes cluster.\",
                \"color\": 5814783,
                \"fields\": [
                  {\"name\": \"📛 Pod Name\", \"value\": \"$POD_NAME\", \"inline\": true},
                  {\"name\": \"📦 Deployment\", \"value\": \"$DEPLOYMENT\", \"inline\": true},
                  {\"name\": \"📍 Namespace\", \"value\": \"$NAMESPACE\", \"inline\": true},
                  {\"name\": \"🔗 URL\", \"value\": \"$PRODUCTION_URL\", \"inline\": false}
                ],
                \"timestamp\": \"$TIMESTAMP\"
              }]
            }" \
            "$WEBHOOK_URL"
        env:
        - name: DISCORD_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: furniaizer-github-client-secret
              key: DISCORD_WEBHOOK_URL
        - name: PRODUCTION_URL
          valueFrom:
            secretKeyRef:
              name: furniaizer-github-client-secret
              key: PRODUCTION_URL
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      containers:
      - name: backend
        image: ghcr.io/teamshackathon/prod/ai-agent-2-backend:latest
        imagePullPolicy: Always
        command: ["sh", "-c"]
        args:
          - |
            alembic upgrade head && \
            uvicorn main:app --host 0.0.0.0 --port 8000 --workers 2 --timeout-keep-alive 60 --log-level info
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: ALLOWED_ORIGINS
          value: "https://163.44.125.128"
        - name: OPENAPI_URL
          value: "/api-furniaizer"
        - name: FRONTEND_REDIRECT_URL
          value: "https://163.44.125.128/furniaizer"
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
                name: furniaizer-github-client-secret
                key: github-client-id
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: furniaizer-github-client-secret
              key: github-client-secret
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: furniaizer-github-client-secret
              key: google-api-key
        - name: GOOGLE_CHAT_MODEL
          value: "gemini-2.0-flash"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: furniaizer-github-client-secret
              key: SECRET_KEY
        - name: POSTGRES_SERVER
          valueFrom:
            secretKeyRef:
              name: furniaizer-github-client-secret
              key: POSTGRES_SERVER
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: furniaizer-github-client-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: furniaizer-github-client-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: furniaizer-github-client-secret
              key: POSTGRES_DB
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: furniaizer-github-client-secret
              key: REDIS_HOST        
        - name: POSTGRES_PORT
          value: "5432"
        - name: MONGODB_HOST
          valueFrom:
            secretKeyRef:
              name: furniaizer-github-client-secret
              key: MONGODB_HOST
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: furniaizer-github-client-secret
              key: MONGODB_USERNAME
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: furniaizer-github-client-secret
              key: MONGODB_PASSWORD
        - name: MONGODB_DB_NAME
          valueFrom:
            secretKeyRef:
              name: furniaizer-github-client-secret
              key: MONGODB_DB_NAME
        - name: MINIO_ENDPOINT_URL
          valueFrom:
            secretKeyRef:
              name: furniaizer-github-client-secret
              key: MINIO_ENDPOINT_URL
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: furniaizer-github-client-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: furniaizer-github-client-secret
              key: MINIO_SECRET_ACCESS_KEY
        - name: STORAGE_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: furniaizer-github-client-secret
              key: STORAGE_BUCKET_NAME
        ports:
        - containerPort: 8000
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /api/v1/healthcheck/liveness
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/healthcheck/readiness
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: furniaizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          exec:
            command: ["redis-cli", "ping"]
          initialDelaySeconds: 10
          periodSeconds: 10