apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-agent-2-backend
  namespace: furniaizer
  labels:
    app: ai-agent-2-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-agent-2-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ai-agent-2-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/teamshackathon/prod/ai-agent-2-backend:latest
        imagePullPolicy: Always
        command: ["uvicorn"]
        args: ["main:app", "--host", "0.0.0.0", "--port", "8000"]
        env:
        - name: APP_ENV
          value: "production"
        - name: ALLOWED_ORIGINS
          value: "https://163.44.125.128"
        - name: OPENAPI_URL
          value: "/api-furniaizer"
        - name: FRONTEND_REDIRECT_URL
          value: "https://163.44.125.128/furniaizer/auth/callback"
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
                name: furniaizer-github-client-secret
                key: github-client-id
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: furniaizer-github-client-secret
              key: github-client-secret
        - name: FIREBASE_CREDENTIALS_PATH
          value: "/app/secrets/firebase-credentials.json"
        volumeMounts:
        # Firebase認証情報JSONファイルのマウント
        - name: firebase-credentials
          mountPath: "/app/secrets"
          readOnly: true
        ports:
        - containerPort: 8000
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /api/v1/healthcheck/liveness
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/healthcheck/readiness
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
      volumes:
      # Firebase認証情報のボリューム定義
      - name: firebase-credentials
        secret:
          secretName: furniaizer-firebase-credentials
          items:
          - key: firebase-credentials.json
            path: firebase-credentials.json