apiVersion: v1
kind: Service
metadata:
  name: ai-agent-2-backend-service
  namespace: furniaizer
spec:
  selector:
    app: ai-agent-2-backend
  ports:
  - port: 3004
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: bae-recipe
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  type: ClusterIP